spring.application.name=issue-tracking-app
spring.datasource.url=jdbc:mysql://localhost:3306/issue_tracking_db
spring.datasource.username=root
spring.datasource.password=toor
spring.jpa.generate-ddl=true
server.port=8085
logging.level.org.springframework.jpa=DEBUG
logging.level.org.springframework=DEBUG
